import { AssetReport, Asset } from '@/types/assets';

// PDF generation using jsPDF (client-side) or server-side alternatives
// This provides the data structure for PDF generation

export interface PDFReportData {
  title: string;
  symbol: string;
  assetName: string;
  assetType: string;
  generatedAt: string;
  currentPrice: string;
  priceChange: string;
  sentiment: string;
  riskLevel: string;
  analysis: string;
  prediction: string;
  keyFactors: string[];
  disclaimer: string;
}

export function formatReportForPDF(report: AssetReport, asset: Asset): PDFReportData {
  const priceChangePrefix = report.priceChangePercent24h >= 0 ? '+' : '';

  return {
    title: `Financial Analysis Report`,
    symbol: asset.symbol,
    assetName: asset.name,
    assetType: asset.type.charAt(0).toUpperCase() + asset.type.slice(1),
    generatedAt: new Date(report.generatedAt).toLocaleString(),
    currentPrice: `$${report.currentPrice.toLocaleString(undefined, {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2
    })}`,
    priceChange: `${priceChangePrefix}${report.priceChangePercent24h.toFixed(2)}% (24h)`,
    sentiment: report.sentiment.charAt(0).toUpperCase() + report.sentiment.slice(1),
    riskLevel: report.riskLevel.charAt(0).toUpperCase() + report.riskLevel.slice(1),
    analysis: report.analysis,
    prediction: report.prediction,
    keyFactors: report.keyFactors,
    disclaimer: 'This report is generated by AI for informational purposes only. It does not constitute financial advice. Always conduct your own research and consult with qualified financial advisors before making investment decisions.'
  };
}

// HTML template for server-side PDF generation
export function generatePDFHTML(data: PDFReportData): string {
  const sentimentColor = {
    Bullish: '#10b981',
    Bearish: '#ef4444',
    Neutral: '#6b7280'
  }[data.sentiment] || '#6b7280';

  const riskColor = {
    Low: '#10b981',
    Medium: '#f59e0b',
    High: '#ef4444'
  }[data.riskLevel] || '#6b7280';

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>${data.title} - ${data.symbol}</title>
      <style>
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          background: #0d0d0f;
          color: #ececf1;
          padding: 40px;
          line-height: 1.6;
        }
        .container {
          max-width: 800px;
          margin: 0 auto;
          background: #202123;
          border-radius: 12px;
          padding: 40px;
        }
        .header {
          border-bottom: 1px solid #40414f;
          padding-bottom: 24px;
          margin-bottom: 24px;
        }
        .title {
          font-size: 28px;
          font-weight: bold;
          color: #ffffff;
          margin-bottom: 8px;
        }
        .subtitle {
          color: #8e8ea0;
          font-size: 14px;
        }
        .asset-info {
          display: flex;
          justify-content: space-between;
          align-items: flex-start;
          margin-bottom: 24px;
        }
        .asset-name {
          font-size: 24px;
          font-weight: 600;
          color: #ffffff;
        }
        .asset-type {
          display: inline-block;
          background: rgba(59, 130, 246, 0.2);
          color: #3b82f6;
          padding: 4px 12px;
          border-radius: 4px;
          font-size: 12px;
          text-transform: uppercase;
          margin-top: 8px;
        }
        .price-info {
          text-align: right;
        }
        .current-price {
          font-size: 28px;
          font-weight: bold;
          color: #ffffff;
        }
        .price-change {
          font-size: 16px;
          margin-top: 4px;
        }
        .metrics {
          display: flex;
          gap: 24px;
          margin-bottom: 32px;
          padding: 20px;
          background: #343541;
          border-radius: 8px;
        }
        .metric {
          flex: 1;
        }
        .metric-label {
          font-size: 12px;
          color: #8e8ea0;
          text-transform: uppercase;
          margin-bottom: 8px;
        }
        .metric-value {
          font-size: 18px;
          font-weight: 600;
        }
        .section {
          margin-bottom: 28px;
        }
        .section-title {
          font-size: 14px;
          font-weight: 600;
          color: #8e8ea0;
          text-transform: uppercase;
          letter-spacing: 0.05em;
          margin-bottom: 12px;
        }
        .section-content {
          color: #ececf1;
          font-size: 15px;
        }
        .key-factors {
          list-style: none;
        }
        .key-factors li {
          padding: 8px 0;
          border-bottom: 1px solid #40414f;
          display: flex;
          align-items: flex-start;
          gap: 12px;
        }
        .key-factors li:last-child {
          border-bottom: none;
        }
        .bullet {
          color: #3b82f6;
          font-size: 18px;
        }
        .disclaimer {
          margin-top: 40px;
          padding: 16px;
          background: #343541;
          border-radius: 8px;
          font-size: 12px;
          color: #8e8ea0;
        }
        .footer {
          margin-top: 32px;
          padding-top: 16px;
          border-top: 1px solid #40414f;
          font-size: 12px;
          color: #565869;
          text-align: center;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <div class="title">${data.title}</div>
          <div class="subtitle">Generated: ${data.generatedAt}</div>
        </div>

        <div class="asset-info">
          <div>
            <div class="asset-name">${data.symbol} - ${data.assetName}</div>
            <div class="asset-type">${data.assetType}</div>
          </div>
          <div class="price-info">
            <div class="current-price">${data.currentPrice}</div>
            <div class="price-change" style="color: ${data.priceChange.startsWith('+') ? '#10b981' : '#ef4444'}">
              ${data.priceChange}
            </div>
          </div>
        </div>

        <div class="metrics">
          <div class="metric">
            <div class="metric-label">Sentiment</div>
            <div class="metric-value" style="color: ${sentimentColor}">${data.sentiment}</div>
          </div>
          <div class="metric">
            <div class="metric-label">Risk Level</div>
            <div class="metric-value" style="color: ${riskColor}">${data.riskLevel}</div>
          </div>
        </div>

        <div class="section">
          <div class="section-title">Analysis</div>
          <div class="section-content">${data.analysis}</div>
        </div>

        <div class="section">
          <div class="section-title">Prediction</div>
          <div class="section-content">${data.prediction}</div>
        </div>

        <div class="section">
          <div class="section-title">Key Factors</div>
          <ul class="key-factors">
            ${data.keyFactors.map(factor => `
              <li>
                <span class="bullet">•</span>
                <span>${factor}</span>
              </li>
            `).join('')}
          </ul>
        </div>

        <div class="disclaimer">
          <strong>Disclaimer:</strong> ${data.disclaimer}
        </div>

        <div class="footer">
          FinDash Financial Dashboard | AI-Powered Analysis
        </div>
      </div>
    </body>
    </html>
  `;
}
